"""initial

Revision ID: 326fefe65ac4
Revises: 
Create Date: 2026-08-18 01:37:41.783205
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '326fefe65ac4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DOCUMENTS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=50), nullable=False),
    sa.Column('page_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')", name='ck_doc_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_type_page', 'DOCUMENTS', ['document_type_code', 'page_key'], unique=False)
    op.create_index(op.f('ix_DOCUMENTS_created_at'), 'DOCUMENTS', ['created_at'], unique=False)
    op.create_index(op.f('ix_DOCUMENTS_status'), 'DOCUMENTS', ['status'], unique=False)
    op.create_table('DOCUMENT_TYPES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)', name='ck_doc_type_active'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DOCUMENT_TYPES_code'), 'DOCUMENT_TYPES', ['code'], unique=True)
    op.create_index(op.f('ix_DOCUMENT_TYPES_is_active'), 'DOCUMENT_TYPES', ['is_active'], unique=False)
    op.create_table('DOCUMENT_TEMPLATES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_json', sa.JSON(), nullable=False),
    sa.Column('extraction_instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)', name='ck_dt_active'),
    sa.ForeignKeyConstraint(['document_type_id'], ['DOCUMENT_TYPES.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type_id', 'page_key', 'version', name='uq_dt_type_page_version')
    )
    op.create_index('idx_dt_active_lookup', 'DOCUMENT_TEMPLATES', ['document_type_id', 'page_key', 'is_active'], unique=False)
    op.create_index('idx_dt_type_page', 'DOCUMENT_TEMPLATES', ['document_type_id', 'page_key'], unique=False)
    op.create_index(op.f('ix_DOCUMENT_TEMPLATES_document_type_id'), 'DOCUMENT_TEMPLATES', ['document_type_id'], unique=False)
    op.create_index('uq_one_active_template_per_page', 'DOCUMENT_TEMPLATES', [sa.text('(CASE WHEN is_active = 1 THEN document_type_id ELSE NULL END)'), sa.text('(CASE WHEN is_active = 1 THEN page_key ELSE NULL END)')], unique=True)  # Extra outer parens: Postgres requires expression-index columns to be parenthesized; Oracle accepts the redundant parens too, so this stays portable.
    op.create_table('PROCESSING_JOBS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_code', sa.String(length=50), nullable=False),
    sa.Column('page_key', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=100), nullable=True),
    sa.Column('ocr_version', sa.String(length=100), nullable=True),
    sa.Column('ai_engine', sa.String(length=100), nullable=True),
    sa.Column('ai_model', sa.String(length=200), nullable=True),
    sa.Column('overall_confidence', sa.Float(precision=4), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'PROCESSING', 'OCR_PROCESSING', 'AI_PROCESSING', 'VALIDATING', 'COMPLETED', 'FAILED')", name='ck_pj_status'),
    sa.ForeignKeyConstraint(['document_id'], ['DOCUMENTS.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['DOCUMENT_TEMPLATES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PROCESSING_JOBS_created_at'), 'PROCESSING_JOBS', ['created_at'], unique=False)
    op.create_index(op.f('ix_PROCESSING_JOBS_document_id'), 'PROCESSING_JOBS', ['document_id'], unique=False)
    op.create_index(op.f('ix_PROCESSING_JOBS_document_type_code'), 'PROCESSING_JOBS', ['document_type_code'], unique=False)
    op.create_index(op.f('ix_PROCESSING_JOBS_status'), 'PROCESSING_JOBS', ['status'], unique=False)
    op.create_table('PROCESSING_RESULTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('extracted_json', sa.JSON(), nullable=False),
    sa.Column('confidence_json', sa.JSON(), nullable=False),
    sa.Column('ocr_metadata_json', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['PROCESSING_JOBS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PROCESSING_RESULTS_job_id'), 'PROCESSING_RESULTS', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PROCESSING_RESULTS_job_id'), table_name='PROCESSING_RESULTS')
    op.drop_table('PROCESSING_RESULTS')
    op.drop_index(op.f('ix_PROCESSING_JOBS_status'), table_name='PROCESSING_JOBS')
    op.drop_index(op.f('ix_PROCESSING_JOBS_document_type_code'), table_name='PROCESSING_JOBS')
    op.drop_index(op.f('ix_PROCESSING_JOBS_document_id'), table_name='PROCESSING_JOBS')
    op.drop_index(op.f('ix_PROCESSING_JOBS_created_at'), table_name='PROCESSING_JOBS')
    op.drop_table('PROCESSING_JOBS')
    op.drop_index('uq_one_active_template_per_page', table_name='DOCUMENT_TEMPLATES')
    op.drop_index(op.f('ix_DOCUMENT_TEMPLATES_document_type_id'), table_name='DOCUMENT_TEMPLATES')
    op.drop_index('idx_dt_type_page', table_name='DOCUMENT_TEMPLATES')
    op.drop_index('idx_dt_active_lookup', table_name='DOCUMENT_TEMPLATES')
    op.drop_table('DOCUMENT_TEMPLATES')
    op.drop_index(op.f('ix_DOCUMENT_TYPES_is_active'), table_name='DOCUMENT_TYPES')
    op.drop_index(op.f('ix_DOCUMENT_TYPES_code'), table_name='DOCUMENT_TYPES')
    op.drop_table('DOCUMENT_TYPES')
    op.drop_index(op.f('ix_DOCUMENTS_status'), table_name='DOCUMENTS')
    op.drop_index(op.f('ix_DOCUMENTS_created_at'), table_name='DOCUMENTS')
    op.drop_index('idx_doc_type_page', table_name='DOCUMENTS')
    op.drop_table('DOCUMENTS')
    # ### end Alembic commands ###
