"""update_documents_template_id

Revision ID: d367297dc546
Revises: b2c3d4e5f6a7
Create Date: 2026-10-07 01:51:30.234934
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.db.database import OracleJSON

revision: str = 'd367297dc546'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_dept_slug', table_name='DEPARTMENTS')
    op.drop_constraint('uq_dept_slug', 'DEPARTMENTS', type_='unique')
    op.create_index(op.f('ix_DEPARTMENTS_slug'), 'DEPARTMENTS', ['slug'], unique=True)
    op.add_column('DOCUMENTS', sa.Column('template_id', sa.Integer(), nullable=False))
    op.drop_index('idx_doc_type_page', table_name='DOCUMENTS')
    op.create_index(op.f('ix_DOCUMENTS_template_id'), 'DOCUMENTS', ['template_id'], unique=False)
    op.create_foreign_key(None, 'DOCUMENTS', 'TEMPLATES', ['template_id'], ['id'])
    op.drop_column('DOCUMENTS', 'page_key')
    op.drop_column('DOCUMENTS', 'document_type_code')
    op.create_index(op.f('ix_DOCUMENT_PAGES_document_id'), 'DOCUMENT_PAGES', ['document_id'], unique=False)
    op.create_index(op.f('ix_FIELD_EXTRACTIONS_job_id'), 'FIELD_EXTRACTIONS', ['job_id'], unique=False)
    op.create_index(op.f('ix_PIPELINE_RUNS_job_id'), 'PIPELINE_RUNS', ['job_id'], unique=False)
    op.create_index(op.f('ix_PROCESSING_EVENTS_created_at'), 'PROCESSING_EVENTS', ['created_at'], unique=False)
    op.create_index(op.f('ix_PROCESSING_EVENTS_job_id'), 'PROCESSING_EVENTS', ['job_id'], unique=False)
    op.alter_column('PROCESSING_JOBS', 'overall_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_PROCESSING_JOBS_document_type_code', table_name='PROCESSING_JOBS')
    op.create_index(op.f('ix_PROCESSING_JOBS_template_id'), 'PROCESSING_JOBS', ['template_id'], unique=False)
    op.drop_constraint('PROCESSING_JOBS_template_id_fkey', 'PROCESSING_JOBS', type_='foreignkey')
    op.create_foreign_key(None, 'PROCESSING_JOBS', 'TEMPLATES', ['template_id'], ['id'])
    op.drop_column('PROCESSING_JOBS', 'page_key')
    op.drop_column('PROCESSING_JOBS', 'document_type_code')
    op.drop_index('idx_dt_active_lookup', table_name='DOCUMENT_TEMPLATES')
    op.drop_index('idx_dt_type_page', table_name='DOCUMENT_TEMPLATES')
    op.drop_index('ix_DOCUMENT_TEMPLATES_document_type_id', table_name='DOCUMENT_TEMPLATES')
    op.drop_index('uq_one_active_template_per_page', table_name='DOCUMENT_TEMPLATES')
    op.drop_table('DOCUMENT_TEMPLATES')
    op.drop_index('idx_doc_type_dept', table_name='DOCUMENT_TYPES')
    op.drop_index('ix_DOCUMENT_TYPES_code', table_name='DOCUMENT_TYPES')
    op.drop_index('ix_DOCUMENT_TYPES_is_active', table_name='DOCUMENT_TYPES')
    op.drop_table('DOCUMENT_TYPES')
    op.alter_column('PROCESSING_RESULTS', 'extracted_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=OracleJSON(),
               existing_nullable=False)
    op.alter_column('PROCESSING_RESULTS', 'confidence_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=OracleJSON(),
               existing_nullable=False)
    op.alter_column('PROCESSING_RESULTS', 'ocr_metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=OracleJSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_TABLE_EXTRACTIONS_job_id'), 'TABLE_EXTRACTIONS', ['job_id'], unique=False)

    op.create_index(op.f('ix_TEMPLATES_department_id'), 'TEMPLATES', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TEMPLATES_department_id'), table_name='TEMPLATES')
    op.drop_index('uq_one_active_tmpl_per_code', table_name='TEMPLATES')
    op.create_index('uq_one_active_tmpl_per_code', 'TEMPLATES', [sa.text('(\nCASE\n    WHEN is_active = 1 THEN department_id\n    ELSE NULL::integer\nEND)'), sa.text('(\nCASE\n    WHEN is_active = 1 THEN code\n    ELSE NULL::character varying\nEND)')], unique=True)
    op.drop_index(op.f('ix_TABLE_EXTRACTIONS_job_id'), table_name='TABLE_EXTRACTIONS')
    op.alter_column('PROCESSING_RESULTS', 'ocr_metadata_json',
               existing_type=app.db.database.OracleJSON(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('PROCESSING_RESULTS', 'confidence_json',
               existing_type=app.db.database.OracleJSON(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('PROCESSING_RESULTS', 'extracted_json',
               existing_type=app.db.database.OracleJSON(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('PROCESSING_JOBS', sa.Column('document_type_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('PROCESSING_JOBS', sa.Column('page_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'PROCESSING_JOBS', type_='foreignkey')
    op.create_foreign_key('PROCESSING_JOBS_template_id_fkey', 'PROCESSING_JOBS', 'DOCUMENT_TEMPLATES', ['template_id'], ['id'])
    op.drop_index(op.f('ix_PROCESSING_JOBS_template_id'), table_name='PROCESSING_JOBS')
    op.create_index('ix_PROCESSING_JOBS_document_type_code', 'PROCESSING_JOBS', ['document_type_code'], unique=False)
    op.alter_column('PROCESSING_JOBS', 'overall_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_PROCESSING_EVENTS_job_id'), table_name='PROCESSING_EVENTS')
    op.drop_index(op.f('ix_PROCESSING_EVENTS_created_at'), table_name='PROCESSING_EVENTS')
    op.drop_index(op.f('ix_PIPELINE_RUNS_job_id'), table_name='PIPELINE_RUNS')
    op.drop_index(op.f('ix_FIELD_EXTRACTIONS_job_id'), table_name='FIELD_EXTRACTIONS')
    op.drop_index(op.f('ix_DOCUMENT_PAGES_document_id'), table_name='DOCUMENT_PAGES')
    op.add_column('DOCUMENTS', sa.Column('document_type_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('DOCUMENTS', sa.Column('page_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'DOCUMENTS', type_='foreignkey')
    op.drop_index(op.f('ix_DOCUMENTS_template_id'), table_name='DOCUMENTS')
    op.create_index('idx_doc_type_page', 'DOCUMENTS', ['document_type_code', 'page_key'], unique=False)
    op.drop_column('DOCUMENTS', 'template_id')
    op.drop_index(op.f('ix_DEPARTMENTS_slug'), table_name='DEPARTMENTS')
    op.create_unique_constraint('uq_dept_slug', 'DEPARTMENTS', ['slug'])
    op.create_index('idx_dept_slug', 'DEPARTMENTS', ['slug'], unique=True)
    op.create_table('DOCUMENT_TEMPLATES',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extraction_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('is_active = ANY (ARRAY[0, 1])', name='ck_dt_active'),
    sa.ForeignKeyConstraint(['document_type_id'], ['DOCUMENT_TYPES.id'], name='DOCUMENT_TEMPLATES_document_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='DOCUMENT_TEMPLATES_pkey'),
    sa.UniqueConstraint('document_type_id', 'page_key', 'version', name='uq_dt_type_page_version')
    )
    op.create_index('uq_one_active_template_per_page', 'DOCUMENT_TEMPLATES', [sa.text('(\nCASE\n    WHEN is_active = 1 THEN document_type_id\n    ELSE NULL::integer\nEND)'), sa.text('(\nCASE\n    WHEN is_active = 1 THEN page_key\n    ELSE NULL::character varying\nEND)')], unique=True)
    op.create_index('ix_DOCUMENT_TEMPLATES_document_type_id', 'DOCUMENT_TEMPLATES', ['document_type_id'], unique=False)
    op.create_index('idx_dt_type_page', 'DOCUMENT_TEMPLATES', ['document_type_id', 'page_key'], unique=False)
    op.create_index('idx_dt_active_lookup', 'DOCUMENT_TEMPLATES', ['document_type_id', 'page_key', 'is_active'], unique=False)
    op.create_table('DOCUMENT_TYPES',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), server_default=sa.text("'GENERAL'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint('is_active = ANY (ARRAY[0, 1])', name='ck_doc_type_active'),
    sa.PrimaryKeyConstraint('id', name='DOCUMENT_TYPES_pkey')
    )
    op.create_index('ix_DOCUMENT_TYPES_is_active', 'DOCUMENT_TYPES', ['is_active'], unique=False)
    op.create_index('ix_DOCUMENT_TYPES_code', 'DOCUMENT_TYPES', ['code'], unique=True)
    op.create_index('idx_doc_type_dept', 'DOCUMENT_TYPES', ['department'], unique=False)
    # ### end Alembic commands ###
